Added theme and initial content [ci skip]

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -7,7 +7,10 @@ set -e
 
 echo "Started deploying"
 
-# Checkout gh-pages branch.
+# Current branch
+currentBranch=`git rev-parse --abbrev-ref HEAD`
+
+# Checkout new gh-pages branch.
 if [ `git branch | grep gh-pages` ]
 then
   git branch -D gh-pages
@@ -22,13 +25,26 @@ find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name '.gitignore' -exec rm 
 mv _site/* .
 rm -R _site/
 
-# Push to gh-pages.
+# Commit
 git add -fA
 git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
-git push -f -q origin gh-pages
+
+# Checkout master
+git checkout master
+
+# Merge in changes
+git merge gh-pages
+
+if [`git ls-files -u`] then
+	echo "Could not merge into master"
+	exit 1
+fi
+
+# Push to github.
+git push -f -q origin
 
 # Move back to previous branch.
-git checkout -
+git checkout $currentBranch
 
 echo "Deployed Successfully!"
 
